### ISSUE TITLE
Beta Release Checklist!

### ISSUE THREAD

**Issue by DrkDevil** [DrkDevil/CleanApp#7]
- [x] Create DropDowns
- [ ] Reimpliment Pill Navbar
- [ ] Create List Groups
- [ ] Create Pagnation
- [ ] Create Progress bars
- [ ] Finish Documentation Pages

**Comment by DrkDevil** [comment]
dead project.
